package com.iwei.wxmanagement.wx;

public class WxRespSetting {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.menu_id
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.message_type
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String messageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.title
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.descrtiptin
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String descrtiptin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.url
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_wx_respset.pic_url
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */
    public String picUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_wx_respset.menu_id
     *
     * @return the value of tb_wx_respset.menu_id
     *
     * @mbggenerated Wed Sep 10 14:07:43 CST 2014
     */

    public String keyWord;
}
