package com.iwei.wxmanagement.wx.dao;

import com.iwei.wxmanagement.wx.member.dto.MemberDTO;

public interface MemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int deleteByPrimaryKey(String id);

    MemberDTO selectById(String id);


    MemberDTO selectByOpenId(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insert(MemberDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insertSelective(MemberDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    MemberDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int updateByPrimaryKeySelective(MemberDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int updateByPrimaryKey(MemberDTO record);
}
