package com.iwei.wxmanagement.wx.dao;

import com.iwei.wxmanagement.wx.dto.WxAccessTokenDTO;

public interface WxAccessTokenDaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int deleteByPrimaryKey(String id);

    WxAccessTokenDTO selectById(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insert(WxAccessTokenDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int insertSelective(WxAccessTokenDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    WxAccessTokenDTO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int updateByPrimaryKeySelective(WxAccessTokenDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated Sun Mar 24 21:49:05 CST 2019
     */
    int updateByPrimaryKey(WxAccessTokenDTO record);
}
